#!/usr/bin/env bash
# Script that will display information about subdomains.
info_dom() {
    domain="$1"
    subdomain="$2"
    sub_domain="${subdomain}.${domain}"
    ip=$(dig "$sub_domain" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')
    record=$(dig "$sub_domain" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')
    echo "The subdomain $subdomain is a $record record and points to $ip"
}
if [[ $# -gt 1 ]]
then
    info_dom "$1" "$2"
elif [[ $# -eq 1 ]]
then
    info_dom "$1" "www"
    info_dom "$1" "lb-01"
    info_dom "$1" "web-01"
    info_dom "$1" "web-02"
fi
