#!/usr/bin/env bash
# Script that transfers a file from our client to a server
if [[ $# -ne 4 ]]; then
    echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
