#!/usr/bin/env bash
# script that configures a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
