#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update
apt -y upgrade
apt -y install nginx

mkdir -p /var/www/html/

file=/var/www/html/index.html
file_re=/etc/nginx/sites-available/default

echo 'server {
    listen 80;
    server_name _;

    location /redirect_me {
	return 301 https://intranet.alxswe.com/;
    }

    location / {
	root /var/www/html;
	index index.html;
	error_page 404 /error.html;
    }
}' | tee $file_re

echo "Ceci n'est pas une page" | tee /var/www/html/error.html

bash -c "echo 'Hello, World!' > $file"
service nginx restart
