#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains :
# the string Ceci n'est pas une page.

apt-get update
apt-get install -y nginx
service nginx restart
mkdir -p /var/www/html/
echo "Hello World!" | tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | tee /var/www/html/404.html > /dev/null

redirect_url="https://github.com/zguaidh"
printf '%s\n' "server {
	listen 80;
	listen [::]:80;

	server_name habibaz.tech www.habibaz.tech;
	root /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 $redirect_url;
	}
	
	error_page 404 /404.html;

	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
