#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update
apt -y upgrade
apt -y install nginx

mkdir -p /var/www/html/

index_file="/var/www/html/index.html"
nginx_file="/etc/nginx/sites-available/default"

cat <<EOF > "$nginx_config"
server {
    listen 80;
    server_name _;

    location /redirect_me {
	return 301 https://intranet.alxswe.com/;
    }

    location / {
	root /var/www/html;
	index index.html;
	error_page 404 /error.html;
    }
}
EOF

echo "Ceci n'est pas une page" > /var/www/html/error.html

echo 'Hello, World!' > "$file"
service nginx restart
