#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/intranet.alxswe.com permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
