#!/usr/bin/env bash
#  script to instal and configure HAProxy on lb-01 
sudo apt-get -y update
sudo apt-get -y install haproxy


s_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 176572-web-01 54.165.168.252:80 check
        server 176572-web-02 34.237.91.136:80 check
"
echo "$s_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy


sudo haproxy -cf /etc/haproxy/haproxy.cfg
