#!/usr/bin/env bash
# finding out what’s keeping the Ubuntu container’s Nginx installation from listening on port 80


# The sites-available directory contains the available configuration files,
# while the sites-enabled directory contains the enabled or active configuration files.
# By creating a symbolic link, any changes made to the default file in the sites-available directory
# will be reflected in the default file in the sites-enabled directory


# To elimenate the erorrs in the previous configuration, let's delete the Nginx configuration file
sudo rm /etc/nginx/sites_enabled/default

# Now let's create a symbolic link between the configuration file (sites-available) and sites-enabled
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart

