#!/usr/bin/env bash
# finding what’s keeping Ubuntu container’s Nginx installation from listening on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill "$(pgrep 'nginx' | head -1)"
