#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
