#!/usr/bin/env bash
# finding what’s keeping Ubuntu container’s Nginx installation from listening on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
