#!/usr/bin/env bash
# script that displays the PID, along with the process name, of processes whose name contain the word bash
pids=$(pidof -x bash)

for pid in $pids; do
	p_name=$(tr '\0' ' ' </proc/"$pid"/cmdline)
	echo "$pid $p_name"
done
