#!/usr/bin/env bash
# This script displays Best School 10 times, but for the 9th iteration,
# +displays Best School and then Hi on a new line.
counter=1
while [ $counter -le 10 ]
do
	if [ $counter == 10 ]
	then
		echo "Hi"
		echo "Best School"
	else
		echo "Best School"
	fi
	counter=$((counter + 1))
done
