#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi
i="0"
while [ $i -lt 10 ]; do
	if [ $i -eq 8 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
