#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
items=$(ls)
IFS=$'\n' read -rd '' -a lines <<<"$items"
for line in "${lines[@]}"
do
	echo "$line" | cut -d '-' -f 2
done
